micronaut:
  application:
    name: propostaRest
  server:
    port: ${SERVER_PORT:8080}

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    manager:
      address: 'localhost:50051'
      plaintext: true
      max-retry-attempts: 10